# Generated by Django 5.2.4 on 2025-07-21 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadia',
            name='turno',
            field=models.CharField(choices=[('12h', '12 horas'), ('18h', '18 horas')], default='12h', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listadia',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='listadia',
            unique_together={('data', 'turno')},
        ),
    ]
