# Generated by Django 5.2.4 on 2025-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_listadia_turno_alter_listadia_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
